
PROJECT_ID          = "hybrid-vertex"
PREFIX              = "rec-bandits-v2"
BUCKET_NAME         = "rec-bandits-v2-hybrid-vertex-bucket"
EXPERIMENT_NAME     = "mab-pipe-rec-bandits-v2"
RUN_NAME            = "run-20231019-184119"
DATA_PATH           = "gs://rec-bandits-v2-hybrid-vertex-bucket/data"
BASE_OUTPUT_DIR     = "gs://rec-bandits-v2-hybrid-vertex-bucket/mab-pipe-rec-bandits-v2/run-20231019-184119"
LOG_DIR             = "gs://rec-bandits-v2-hybrid-vertex-bucket/mab-pipe-rec-bandits-v2/run-20231019-184119/logs"
ROOT_DIR            = "gs://rec-bandits-v2-hybrid-vertex-bucket/mab-pipe-rec-bandits-v2/run-20231019-184119/root"
ARTIFACTS_DIR       = "gs://rec-bandits-v2-hybrid-vertex-bucket/mab-pipe-rec-bandits-v2/run-20231019-184119/artifacts"
DATA_PATH_KFP_DEMO  = "gs://rec-bandits-v2-hybrid-vertex-bucket/data/kfp_demo_data/u.data"
BQ_LOCATION         = "US"
BIGQUERY_DATASET_NAME = "rec_bandits_v2_bucket"
BIGQUERY_TABLE_NAME   = "training_dataset"
