
PROJECT_ID          = "hybrid-vertex"
REGION              = "us-central1"
PREFIX              = "rec-bandits-v2"
BUCKET_NAME         = "rec-bandits-v2-hybrid-vertex-bucket"
EXPERIMENT_NAME     = "mab-pipe-rec-bandits-v2"
RUN_NAME            = "run-20231025-165806"
DATA_PATH           = "gs://rec-bandits-v2-hybrid-vertex-bucket/data"
BASE_OUTPUT_DIR     = "gs://rec-bandits-v2-hybrid-vertex-bucket/mab-pipe-rec-bandits-v2/run-20231025-165806"
LOG_DIR             = "gs://rec-bandits-v2-hybrid-vertex-bucket/mab-pipe-rec-bandits-v2/run-20231025-165806/logs"
ROOT_DIR            = "gs://rec-bandits-v2-hybrid-vertex-bucket/mab-pipe-rec-bandits-v2/run-20231025-165806/root"
ARTIFACTS_DIR       = "gs://rec-bandits-v2-hybrid-vertex-bucket/mab-pipe-rec-bandits-v2/run-20231025-165806/artifacts"
DATA_PATH_KFP_DEMO  = "gs://rec-bandits-v2-hybrid-vertex-bucket/data/kfp_demo_data/u.data"
BQ_LOCATION         = "US"
BIGQUERY_DATASET_NAME = "mvlens_rec_bandits_v2"
BIGQUERY_TABLE_NAME   = "training_dataset"
