
FROM gcr.io/deeplearning-platform-release/tf-gpu.2-13.py310

ENV PYTHONUNBUFFERED True

ENV APP_HOME /workspace

WORKDIR $APP_HOME

COPY /requirements.txt $APP_HOME/requirements.txt

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r $APP_HOME/requirements.txt

RUN ls $APP_HOME

COPY src/reward_factory.py $APP_HOME/src/reward_factory.py
COPY src/train_utils.py $APP_HOME/src/train_utils.py
COPY src/agents $APP_HOME/src/agents
COPY src/networks $APP_HOME/src/networks
COPY src/trainer $APP_HOME/src/trainer
COPY src/data $APP_HOME/src/data

RUN apt update && apt -y install nvtop

RUN ls $APP_HOME

RUN export PYTHONPATH=${PYTHONPATH}:${APP_HOME}/

RUN pip freeze

# Sets up the entry point to invoke the task.
ENTRYPOINT ["python3", "-m", "src.trainer.task"]
