
FROM gcr.io/deeplearning-platform-release/tf2-gpu.2-13.py310

ENV APP_HOME /workspace

WORKDIR $APP_HOME

COPY /requirements.txt $APP_HOME/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r $APP_HOME/requirements.txt
RUN pip install cloudml-hypertune

RUN apt update && apt -y install nvtop

COPY src/policy_util.py $APP_HOME/src/policy_util.py
COPY src/train_utils.py $APP_HOME/src/train_utils.py
COPY src/environments $APP_HOME/src/environments
COPY src/trainer $APP_HOME/src/trainer
COPY src/data $APP_HOME/src/data

RUN export PYTHONPATH=${PYTHONPATH}:${APP_HOME}/

RUN pip freeze | grep wrapt

# Sets up the entry point to invoke the task.
ENTRYPOINT ["python3", "-m", "src.trainer.train_env_task"]
