
PROJECT_ID          = "hybrid-vertex"
REGION              = "us-central1"
PREFIX              = "rec-bandits-v2"
BUCKET_NAME         = "rec-bandits-v2-hybrid-vertex-bucket"
DATA_PIPELINE_IMAGE = "gcr.io/hybrid-vertex/rl-mv-preprocessing"
KFP_SDK_VERSION     = "2.3.0"
GCS_SDK_VERSION     = "2.16.0"
BQ_SDK_VERSION      = "3.11.4"
AIP_SDK_VERSION     = "1.46.0"
